name: Run tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test-plugin:
    env:
      plugin_name: "otio_template_plugin"

    name: "OpenTimelineIO" ${{ matrix.otio-version }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
        otio-version: [0.13, 0.14, 0.14.1, 0.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov -V OpenTimelineIO==${{ matrix.otio-version }}

      - name: Install Plugin
        run: |
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 --show-source --statistics

      - name: Test with pytest
        run: |
          pytest

        shell: bash
